apiVersion: v1
kind: ReplicationController

metadata:
 name: nginx-web
spec:
 replicas: 3
 selector: 
  app: nginxsel
 template:
  metadata:
   name: ng-meta
   labels:
    app: nginxsel

  spec:
   containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
      imagePullPolicy: IfNotPresent
