apiVersion: extensions/v1beta1
kind: Deployment

metadata:
 name: ngipod
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: adhocdep1

  spec:
   containers:
    - name: web2
      image: nginx
      ports:
       - containerPort: 80
      imagePullPolicy: IfNotPresent
