apiVersion: v1
kind: Service
metadata:
 name: nginx-service

spec:
 ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
 type: LoadBalancer
 LoadBalancerIP: "192.168.99.100"
 selector:
  app: nginxsel
